### ISSUE TITLE
Misleading example

### ISSUE THREAD

**Issue by FauxFaux** [aduth/preact-fetching#1]
In the example, you suggest using a key of `#[owner, repo]`. I don't know where this syntax is from, but I'm reasonably sure it's not JS or TS.

If you run the example with `[owner, repo]` as the key, it goes into an infinite loop, I think because arrays are always distinct as map keys:

```
> const a = "a";
> m = new Map();
Map(0) {}
> m.set([a], 2);
Map(1) { [ 'a' ] => 2 }
> m.set([a], 3);
Map(2) { [ 'a' ] => 2, [ 'a' ] => 3 }
```

A key of `${owner}/${repo}` may be more appropriate, and more, y'know, working.

It took me an unreasonable amount of time to figure this out.

**Comment by aduth** [comment]
Fair enough. The syntax is the [stage 2 Tuple language proposal](https://github.com/tc39/proposal-record-tuple), but I suppose a current-day syntax example is more generally useful. Updated in 9e47649. Thanks for the feedback.
