### ISSUE TITLE
Be able to cancel the request

### ISSUE THREAD

**Issue by aminnairi** [aduth/preact-fetching#2]
Hi Aduth!

Thank you for making this lightweight library.

One thing that would be awesome to support would be the [AbortController API](https://developer.mozilla.org/en-US/docs/Web/API/AbortController).

Are you planning on adding this feature for your library?

Thank you for your reply and happy new year!

**Comment by aduth** [comment]
Hey @aminnairi , thanks for the suggestion. Could you tell me a bit more about how you might expect it to work?

In the spirit of keeping the library light, is it something which could be accomplished with a wrapper hook?

Maybe something like...

```ts
function useCancelableFetch(url) {
  const controller = new AbortController();
  const result = useQuery(url, () => fetch(url, { signal: controller.signal }));
  return { ...result, controller };
}

// ...

const { controller } = useCancelableFetch('https://example.com');
controller.abort();
```

**Comment by aminnairi** [comment]
You are correct, since we are in control of the promise once could use an `AbortController` in the callbak passed to `useQuery` and create his own hook. Thanks for you reply!
