### ISSUE TITLE
deno fresh

### ISSUE THREAD

**Issue by abdulbasetbasher** [aduth/preact-fetching#3]
when i use it with fresh framework using ```import { useQuery } from "npm:preact-fetching";```

it's give me error

```
Cannot read properties of undefined (reading 'context')
```

but when copy the file in project it works

**Comment by aduth** [comment]
Hi! Thanks for the report. I'm not very familiar with Deno, so could you provide me some more information to help debug what might be going on here?

- Code of how you're using `preact-fetching`, or a minimally viable example which causes the error. Is the `import` alone enough to cause the error?
- The full stack trace of the error
- Deno version

**Comment by abdulbasetbasher** [comment]
actually i got it work.

the problem was preact-fetching import preact as internal dependency, but in deno not working like node, so we need to configure the module so that preact is referenced as an external dependency.

this full working code for deno fresh client side island

```
import { useQuery } from "https://esm.sh/preact-fetching@1.0.0?external=preact";

export default function Page() {
	const { isLoading, isError, error, data } = useQuery(`xx`, async () => {
		const response = await fetch(`https://api.github.com/repos/aduth/preact-fetching`);
		const data = await response.json();
		return data.stargazers_count;
	});

	if (isError) {
		return (
            <div>{error.message}</div>
        )
	}

	if (isLoading) {
		return (
            <div>loading..</div>
        )
	}

	return (
        <div>Count: {data}</div>
    )
}
```

**Comment by aduth** [comment]
Great, glad you were able to get it working 👍 

I'll close the issue, but let me know if you run into any other problems.
